/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContents: typeof import('./src/components/AppContents.vue')['default']
    Description: typeof import('./src/components/sections/Description.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    Flicker: typeof import('./src/components/sections/Flicker.vue')['default']
    Footer: typeof import('./src/components/sections/Footer.vue')['default']
    NMap: typeof import('./src/components/sections/NMap.vue')['default']
    Pictures: typeof import('./src/components/sections/Pictures.vue')['default']
    Subject: typeof import('./src/components/sections/Subject.vue')['default']
  }
}
